package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table(name = "citation")
public class CitationTable extends TableEntity<Integer> {

	@PrimaryKey @Column(name = "id") @Autogenerated private final Integer id;
	@Column(name = "location") private final String location;
	@Column(name = "timestamp") private final Integer timestamp;
	@Column(name = "message") private final String message;
	@Column(name = "doctor") private final Integer doctorId;
	@Column(name = "patient") private final Integer patientId;
	
	public CitationTable() {
		this(null, null, null, null, null, null);
	}
	
	public CitationTable(Integer id, Integer timestamp, String location, String message, Integer doctorId, Integer patientId) {
		super();
		this.id = id;
		this.timestamp = timestamp;
		this.message = message;
		this.location = location;
		this.doctorId = doctorId;
		this.patientId = patientId;
	}

	public Integer getId() {
		return id;
	}

	public String getLocation() {
		return location;
	}

	public Integer getTimestamp() {
		return timestamp;
	}

	public String getMessage() {
		return message;
	}

	public Integer getDoctorId() {
		return doctorId;
	}

	public Integer getPatientId() {
		return patientId;
	}
	
}
