package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table(name = "patient_doctor")
public class PatientDoctorTable extends TableEntity<Integer> {

	@PrimaryKey @Column(name = "id") @Autogenerated private final Integer id;
	@Column(name = "patient") private final Integer patientId;
	@Column(name = "doctor") private final Integer doctorId;
	
	public PatientDoctorTable() {
		this(null, null, null);
	}
	
	public PatientDoctorTable(Integer id, Integer patientId, Integer doctorId) {
		super();
		this.id = id;
		this.patientId = patientId;
		this.doctorId = doctorId;
	}

	public Integer getId() {
		return id;
	}

	public Integer getPatientId() {
		return patientId;
	}

	public Integer getDoctorId() {
		return doctorId;
	}
	
}
