package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table("patient_sensor")
public class PatientSensorTable extends TableEntity<Integer> {

	@PrimaryKey @Column("id") @Autogenerated private final Integer id;
	@Column("patient") private final Integer patient;
	@Column("name") private final String name;
	
	public PatientSensorTable() {
		this(null, null, null);
	}
	
	public PatientSensorTable(Integer id, Integer patient, String sensorName) {
		super();
		this.id = id;
		this.patient = patient;
		this.name = sensorName;
	}

	public Integer getPatient() {
		return patient;
	}
	
	public String getSensorName() {
		return name;
	}
	
}
