package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table(name = "patient_sensor")
public class PatientSensorTable extends TableEntity<Integer> {

	@PrimaryKey @Column(name = "id") @Autogenerated private final Integer id;
	@Column(name = "patient") private final Integer patientId;
	@Column(name = "sensor") private final Integer sensorId;
	
	public PatientSensorTable() {
		this(null, null, null);
	}
	
	public PatientSensorTable(Integer id, Integer patientId, Integer sensorId) {
		super();
		this.id = id;
		this.patientId = patientId;
		this.sensorId = sensorId;
	}

	public Integer getPatientId() {
		return patientId;
	}
	
	public Integer getSensorId() {
		return sensorId;
	}
	
}
