package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table("patient_carer")
public class PatientCarerTable extends TableEntity<Integer> {

	@PrimaryKey @Column("id") @Autogenerated private final Integer id;
	@Column("patient") private final Integer patient;
	@Column("carer") private final Integer carer;
	
	public PatientCarerTable() {
		this(null, null, null);
	}
	
	public PatientCarerTable(Integer id, Integer patient, Integer carer) {
		super();
		this.id = id;
		this.patient = patient;
		this.carer = carer;
	}

	public Integer getId() {
		return id;
	}

	public Integer getPatient() {
		return patient;
	}

	public Integer getCarer() {
		return carer;
	}
	
}
