package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table(name = "sensor_data")
public class SensorDataTable extends TableEntity<Integer> {

	@PrimaryKey @Column(name = "id") @Autogenerated private final Integer id;
	@Column(name = "sensor") private final Integer sensorId;
	@Column(name = "timestamp") private final Long timestamp;
	@Column(name = "value") private final Double value;
	
	public SensorDataTable() {
		this(null, null, null, null);
	}
	
	public SensorDataTable(Integer id, Integer sensorId, Long timestamp, Double value) {
		super();
		this.id = id;
		this.sensorId = sensorId;
		this.timestamp = timestamp;
		this.value = value;
	}

	public Integer getSensorId() {
		return sensorId;
	}
	
	public Long getTimestamp() {
		return timestamp;
	}
	
	public Double getValue() {
		return value;
	}
	
}
