package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table("sensor_data")
public class SensorDataTable extends TableEntity<Integer> {

	@PrimaryKey @Column("id") @Autogenerated private final Integer id;
	@Column("sensor") private final Integer sensor;
	@Column("timestamp") private final Long timestamp;
	@Column("value") private final Double value;
	
	public SensorDataTable() {
		this(null, null, null, null);
	}
	
	public SensorDataTable(Integer id, Integer sensor, Long timestamp, Double value) {
		super();
		this.id = id;
		this.sensor = sensor;
		this.timestamp = timestamp;
		this.value = value;
	}

	public Integer getSensor() {
		return sensor;
	}
	
	public Long getTimestamp() {
		return timestamp;
	}
	
	public Double getValue() {
		return value;
	}
	
}
