package com.magc.sensecane.server.model.database;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table("user") public class UserTable extends TableEntity<Integer> {

	@PrimaryKey @Autogenerated @Column("id") private final Integer id;
	
	public UserTable() {
		this(null);
	}
	
	public UserTable(Integer id) {
		super();
		this.id = id;
	}
}
